<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\menu_link_content\Entity\MenuLinkContent;
use Drupal\menu_section\MenuSectionFormNodeFormAlter;
use Drupal\system\Entity\Menu;

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function menu_section_node_insert(EntityInterface $entity) {
  /** @var \Drupal\node\NodeInterface $entity */
  if (in_array($entity->bundle(), \Drupal::config('menu_section.settings')->get('section_types'))) {
    $menu_name = preg_replace('/[^a-z0-9-]+/', '-', $entity->bundle()) . '--' . $entity->id();
    Menu::create([
      'id' => $menu_name,
      'label' => $entity->label(),
      'third_party_settings' => ['menu_section' => ['uid' => $entity->getOwnerId()]],
    ])->save();
    MenuLinkContent::create([
      'link' => [['uri' => 'entity:node/' . $entity->id()]],
      'title' => t('Home'),
      'menu_name' => $menu_name,
    ])->save();
  }
}

function menu_section_form_node_form_alter(&$form, FormStateInterface $formState) {
  MenuSectionFormNodeFormAlter::alter($form, $formState->getFormObject()->getEntity());
}
